# Generated by Django 2.0.6 on 2018-06-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boycott', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='bDel',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
